### ISSUE TITLE
STOPPED: error in input or during the segmentation

### ISSUE THREAD

**Issue by Cstewski** [MedicalImageAnalysisTutorials/SlicerCervicalSpine#5]
Hello Dr Al-Dhamari,

My name is Caleb Stewart. I am using your software program for segmenting the cervical spine from an MRI scan (MPRAGE sequence). Can you explain what this error message means below from 3D slicer? I attached an image of my screen and followed the directions from your YouTube video without any success. A video recording of MR example may be helpful. Thank you.

Kindly

Caleb

Defaults paths:
VisSimTools folder: C:\Users\Ochsner_m3D\VisSimTools
Output folder : C:\Users\Ochsner_m3D\VisSimTools\outputs
elastix binaries are found in C:\Users\Ochsner_m3D\AppData\Roaming\NA-MIC\Extensions-28257\SlicerElastix\lib\Slicer-4.10/elastix.exe
Spine Extension is selected
sha256computedCheckSum: 9a2ee6a67a190e438a18be811310cbf4eb26b6ad3e00243affa44cc0b26c4393
Model folder is found...
Parameter file: C:\Users\Ochsner_m3D\VisSimTools\pars\parSpiSeg.txt
Cropping Length: [ 80 , 80 , 50 ]
setup local paths variables.........................
STOPPED: error in input or during the segmentation
'NoneType' object has no attribute 'GetFileName'

**Comment by idhamari** [comment]
COuld you please try:
1. save the image as nrrd format with this name: imgMRI
   - notice that there is no space or special characters in the file name or the path 
   - save the image in your  Downloads folder
2. Close slicer and open it again. Then load the saved image.  
3. Try the extension.
4. Report what happened by replying here.

**Comment by idhamari** [comment]
Also, check if you are using the extension correctly:

https://www.youtube.com/watch?v=GX8FQMkhRuU

**Comment by idhamari** [comment]
It is been a few days, I will assume your problem is solved and close this issue. In case you still have a problem please re-open the issue and add feedback.
